import type { OfficeLook } from "./office-looks";

/** Original office ensemble: agency, technology, leadership, publishing and negotiation. */
export const EXTENDED_OFFICE_LOOKS: readonly OfficeLook[] = [
  {
    id: "office-nari",
    name: "나리",
    nameEn: "Nari",
    category: "creative",
    subtitle: "광고 기획자 · 리본 블라우스와 무릎 스커트",
    subtitleEn: "Account planner · bow blouse and knee skirt",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#302526",
    hairStyle: "bob",
    outfit: "blouse",
    coat: "#d0a993",
    shirt: "#f3dfcc",
    trousers: "#625862",
    shoes: "#453433",
    build: 0.96,
    stance: "bright",
    bodyType: "female",
    neckwear: "bow",
    lower: "skirt",
    skirtLength: "knee",
    accessory: "notebook",
  },
  {
    id: "office-roan",
    name: "로안",
    nameEn: "Roan",
    category: "creative",
    subtitle: "아트디렉터 · 검은 터틀넥과 체크 코트",
    subtitleEn: "Art director · black turtleneck and checked coat",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#262220",
    hairStyle: "wave",
    outfit: "coat",
    coat: "#857b6d",
    shirt: "#252e2b",
    trousers: "#4e514b",
    shoes: "#342d29",
    build: 1.12,
    stance: "relaxed",
    bodyType: "male",
    neckwear: "turtleneck",
    pattern: "check",
    glasses: true,
    bag: "shoulder",
  },
  {
    id: "office-soi",
    name: "소이",
    nameEn: "Soi",
    category: "creative",
    subtitle: "브랜드 전략가 · 올림머리와 더블 재킷",
    subtitleEn: "Brand strategist · bun and double-breasted jacket",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#784932",
    hairStyle: "bun",
    outfit: "double-breasted",
    coat: "#855748",
    shirt: "#ede1cc",
    trousers: "#aaa18a",
    shoes: "#4b3b35",
    build: 1.01,
    stance: "composed",
    bodyType: "female",
    lower: "wide",
    accessory: "notebook",
  },
  {
    id: "office-yul",
    name: "율",
    nameEn: "Yul",
    category: "creative",
    subtitle: "카피라이터 · 곱슬머리와 니트 베스트",
    subtitleEn: "Copywriter · curls and knitted vest",
    skin: "#795037",
    skinVariant: "black",
    hair: "#252525",
    hairStyle: "curls",
    outfit: "vest",
    coat: "#a88749",
    shirt: "#e6d6b5",
    trousers: "#4d5860",
    shoes: "#41403a",
    build: 1.18,
    stance: "bright",
    bodyType: "male",
    pattern: "knit",
    glasses: true,
    bag: "backpack",
  },
  {
    id: "office-bomi",
    name: "보미",
    nameEn: "Bomi",
    category: "creative",
    subtitle: "콘텐츠 프로듀서 · 땋은 머리와 긴 치마",
    subtitleEn: "Content producer · braids and long skirt",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#3c2923",
    hairStyle: "braids",
    outfit: "cardigan",
    coat: "#688270",
    shirt: "#f3e8cf",
    trousers: "#bd9c79",
    shoes: "#5c493d",
    build: 0.97,
    stance: "relaxed",
    bodyType: "female",
    lower: "skirt",
    skirtLength: "long",
    pattern: "knit",
    bag: "shoulder",
  },
  {
    id: "office-jiho",
    name: "지호",
    nameEn: "Jiho",
    category: "casual",
    subtitle: "촬영 감독 · 셔츠와 현장 헤드셋",
    subtitleEn: "Production director · shirt and on-set headset",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#292d29",
    hairStyle: "crop",
    outfit: "shirt",
    coat: "#8b9ba0",
    shirt: "#8b9ba0",
    trousers: "#505747",
    shoes: "#41382e",
    build: 1.26,
    stance: "relaxed",
    bodyType: "male",
    accessory: "headset",
    bag: "backpack",
    lower: "wide",
  },
  {
    id: "office-dami",
    name: "다미",
    nameEn: "Dami",
    category: "creative",
    subtitle: "캠페인 매니저 · 스카프와 짧은 단발",
    subtitleEn: "Campaign manager · scarf and cropped bob",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#2f2624",
    hairStyle: "bob",
    outfit: "suit",
    coat: "#647482",
    shirt: "#e6c7b5",
    trousers: "#647482",
    shoes: "#343c40",
    build: 1.08,
    stance: "bright",
    bodyType: "female",
    neckwear: "scarf",
    accessory: "badge",
    bag: "briefcase",
  },
  {
    id: "office-seul",
    name: "슬아",
    nameEn: "Seula",
    category: "creative",
    subtitle: "디자인 리서처 · 긴 머리와 넉넉한 니트",
    subtitleEn: "Design researcher · long hair and roomy knit",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#675346",
    hairStyle: "long",
    outfit: "cardigan",
    coat: "#be9266",
    shirt: "#f4e8d4",
    trousers: "#70685d",
    shoes: "#4b4540",
    build: 1.14,
    stance: "relaxed",
    bodyType: "female",
    pattern: "knit",
    lower: "wide",
    glasses: true,
    accessory: "notebook",
  },
  {
    id: "office-kyu",
    name: "규민",
    nameEn: "Kyumin",
    category: "classic",
    subtitle: "클라이언트 파트너 · 줄무늬 수트와 타이",
    subtitleEn: "Client partner · pinstripe suit and tie",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#413a32",
    hairStyle: "part",
    outfit: "suit",
    coat: "#3e5354",
    shirt: "#e8eadc",
    trousers: "#3e5354",
    shoes: "#4d3730",
    build: 0.95,
    stance: "composed",
    bodyType: "male",
    pattern: "pinstripe",
    tie: "#aa7953",
    bag: "briefcase",
  },
  {
    id: "office-ara",
    name: "아라",
    nameEn: "Ara",
    category: "creative",
    subtitle: "행사 디렉터 · 포니테일과 활동적인 베스트",
    subtitleEn: "Event director · ponytail and practical vest",
    skin: "#795037",
    skinVariant: "black",
    hair: "#302522",
    hairStyle: "pony",
    outfit: "vest",
    coat: "#a9654e",
    shirt: "#e7dfce",
    trousers: "#5b555c",
    shoes: "#423638",
    build: 1.03,
    stance: "bright",
    bodyType: "female",
    lower: "wide",
    accessory: "headset",
    bag: "shoulder",
  },
  {
    id: "office-ian",
    name: "이안",
    nameEn: "Ian",
    category: "casual",
    subtitle: "백엔드 개발자 · 안경과 후드 집업",
    subtitleEn: "Backend engineer · glasses and hoodie",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#322b27",
    hairStyle: "crop",
    outfit: "hoodie",
    coat: "#607b69",
    shirt: "#efe8d6",
    trousers: "#4d5863",
    shoes: "#ebe4d5",
    build: 1.17,
    stance: "relaxed",
    bodyType: "male",
    glasses: true,
    bag: "backpack",
  },
  {
    id: "office-rumi",
    name: "루미",
    nameEn: "Rumi",
    category: "casual",
    subtitle: "프런트엔드 개발자 · 땋은 머리와 후드",
    subtitleEn: "Frontend engineer · braids and hoodie",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#3d2824",
    hairStyle: "braids",
    outfit: "hoodie",
    coat: "#a17c91",
    shirt: "#ece2d4",
    trousers: "#555a68",
    shoes: "#e2d8ca",
    build: 0.94,
    stance: "bright",
    bodyType: "female",
    bag: "backpack",
    accessory: "headset",
    lower: "wide",
  },
  {
    id: "office-gonu",
    name: "건우",
    nameEn: "Gonu",
    category: "casual",
    subtitle: "QA 엔지니어 · 체크 셔츠와 기록 노트",
    subtitleEn: "QA engineer · checked shirt and notebook",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#353a32",
    hairStyle: "part",
    outfit: "shirt",
    coat: "#9ca594",
    shirt: "#9ca594",
    trousers: "#665b49",
    shoes: "#514333",
    build: 1.29,
    stance: "composed",
    bodyType: "male",
    pattern: "check",
    accessory: "notebook",
    glasses: true,
  },
  {
    id: "office-haena",
    name: "해나",
    nameEn: "Haena",
    category: "casual",
    subtitle: "데이터 과학자 · 연구 가운과 올림머리",
    subtitleEn: "Data scientist · lab coat and bun",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#432d28",
    hairStyle: "bun",
    outfit: "labcoat",
    coat: "#eeeade",
    shirt: "#62838b",
    trousers: "#4b5b65",
    shoes: "#343e45",
    build: 1.06,
    stance: "composed",
    bodyType: "female",
    glasses: true,
    accessory: "badge",
  },
  {
    id: "office-woojin",
    name: "우진",
    nameEn: "Woojin",
    category: "casual",
    subtitle: "사내 IT 담당 · 곱슬머리와 넓은 바지",
    subtitleEn: "IT specialist · curls and wide trousers",
    skin: "#795037",
    skinVariant: "black",
    hair: "#2b2926",
    hairStyle: "curls",
    outfit: "shirt",
    coat: "#c7a16c",
    shirt: "#c7a16c",
    trousers: "#666f60",
    shoes: "#433f32",
    build: 1.32,
    stance: "bright",
    bodyType: "male",
    lower: "wide",
    accessory: "headset",
    bag: "backpack",
  },
  {
    id: "office-jua",
    name: "주아",
    nameEn: "Jua",
    category: "creative",
    subtitle: "UX 디자이너 · 물결 머리와 리본 니트",
    subtitleEn: "UX designer · waves and bow-neck cardigan",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#a77850",
    hairStyle: "wave",
    outfit: "cardigan",
    coat: "#aeb9a0",
    shirt: "#f3e4cf",
    trousers: "#696975",
    shoes: "#5b4650",
    build: 0.99,
    stance: "bright",
    bodyType: "female",
    neckwear: "bow",
    pattern: "knit",
    lower: "skirt",
    skirtLength: "knee",
  },
  {
    id: "office-taemin",
    name: "태민",
    nameEn: "Taemin",
    category: "casual",
    subtitle: "스크럼 마스터 · 베스트와 사원증",
    subtitleEn: "Scrum master · sweater vest and badge",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#4c3b30",
    hairStyle: "crop",
    outfit: "vest",
    coat: "#778898",
    shirt: "#e9d9bf",
    trousers: "#725d4d",
    shoes: "#44392f",
    build: 1.11,
    stance: "bright",
    bodyType: "male",
    pattern: "knit",
    accessory: "badge",
    bag: "shoulder",
  },
  {
    id: "office-sera",
    name: "세라",
    nameEn: "Sera",
    category: "casual",
    subtitle: "보안 엔지니어 · 긴 머리와 터틀넥 코트",
    subtitleEn: "Security engineer · long hair and turtleneck coat",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#272a2c",
    hairStyle: "long",
    outfit: "coat",
    coat: "#49565e",
    shirt: "#b8bfaf",
    trousers: "#41484b",
    shoes: "#363737",
    build: 1.04,
    stance: "composed",
    bodyType: "female",
    neckwear: "turtleneck",
    bag: "backpack",
    glasses: true,
  },
  {
    id: "office-hosu",
    name: "호수",
    nameEn: "Hosu",
    category: "casual",
    subtitle: "로봇 연구원 · 짧은 머리와 실험 가운",
    subtitleEn: "Robotics researcher · cropped hair and lab coat",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#6a5345",
    hairStyle: "crop",
    outfit: "labcoat",
    coat: "#e4e7dc",
    shirt: "#b08354",
    trousers: "#58615b",
    shoes: "#45453b",
    build: 1.2,
    stance: "relaxed",
    bodyType: "male",
    accessory: "notebook",
    bag: "backpack",
  },
  {
    id: "office-yena",
    name: "예나",
    nameEn: "Yena",
    category: "creative",
    subtitle: "커뮤니티 매니저 · 단발과 넉넉한 후드",
    subtitleEn: "Community manager · bob and roomy hoodie",
    skin: "#795037",
    skinVariant: "black",
    hair: "#3b2924",
    hairStyle: "bob",
    outfit: "hoodie",
    coat: "#c49256",
    shirt: "#f0debf",
    trousers: "#6a676e",
    shoes: "#ece5d6",
    build: 1.15,
    stance: "bright",
    bodyType: "female",
    lower: "skirt",
    skirtLength: "long",
    accessory: "headset",
  },
  {
    id: "office-sungho",
    name: "성호",
    nameEn: "Sungho",
    category: "leadership",
    subtitle: "운영 총괄 · 실버 가르마와 더블 수트",
    subtitleEn: "Operations chief · silver part and double suit",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#b5b1a3",
    hairStyle: "part",
    outfit: "double-breasted",
    coat: "#394951",
    shirt: "#eee4d2",
    trousers: "#394951",
    shoes: "#2e3335",
    build: 1.26,
    stance: "composed",
    bodyType: "male",
    tie: "#88674f",
    bag: "briefcase",
    pattern: "pinstripe",
  },
  {
    id: "office-hyejin",
    name: "혜진",
    nameEn: "Hyejin",
    category: "leadership",
    subtitle: "재무 책임자 · 올림머리와 차분한 스카프",
    subtitleEn: "Finance chief · bun and restrained scarf",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#52433c",
    hairStyle: "bun",
    outfit: "double-breasted",
    coat: "#675757",
    shirt: "#e1d6bf",
    trousers: "#675757",
    shoes: "#3f3434",
    build: 1.14,
    stance: "composed",
    bodyType: "female",
    neckwear: "scarf",
    lower: "skirt",
    skirtLength: "knee",
    glasses: true,
  },
  {
    id: "office-jungwon",
    name: "정원",
    nameEn: "Jungwon",
    category: "leadership",
    subtitle: "인사 책임자 · 은빛 단발과 긴 니트",
    subtitleEn: "People director · silver bob and long knit",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#c2beb1",
    hairStyle: "bob",
    outfit: "cardigan",
    coat: "#8c9279",
    shirt: "#eee5d5",
    trousers: "#585c52",
    shoes: "#55483c",
    build: 1.22,
    stance: "relaxed",
    bodyType: "female",
    pattern: "knit",
    lower: "wide",
    accessory: "notebook",
  },
  {
    id: "office-seok",
    name: "석현",
    nameEn: "Seokhyun",
    category: "leadership",
    subtitle: "사업 대표 · 웨이브 헤어와 체크 수트",
    subtitleEn: "Business president · waves and checked suit",
    skin: "#795037",
    skinVariant: "black",
    hair: "#77766c",
    hairStyle: "wave",
    outfit: "suit",
    coat: "#71674f",
    shirt: "#e6dec9",
    trousers: "#71674f",
    shoes: "#41382f",
    build: 1.3,
    stance: "composed",
    bodyType: "male",
    pattern: "check",
    tie: "#4b6b61",
    bag: "briefcase",
  },
  {
    id: "office-mira",
    name: "미라",
    nameEn: "Mira",
    category: "leadership",
    subtitle: "크리에이티브 총괄 · 긴 머리와 더블 재킷",
    subtitleEn: "Creative chief · long hair and double jacket",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#46312a",
    hairStyle: "long",
    outfit: "double-breasted",
    coat: "#e0c9a1",
    shirt: "#67564c",
    trousers: "#5d655f",
    shoes: "#493c33",
    build: 1.06,
    stance: "bright",
    bodyType: "female",
    lower: "wide",
    neckwear: "turtleneck",
    bag: "shoulder",
  },
  {
    id: "office-kyung",
    name: "경수",
    nameEn: "Kyungsu",
    category: "leadership",
    subtitle: "법무 책임자 · 정돈된 머리와 쓰리피스",
    subtitleEn: "General counsel · neat crop and tailored vest",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#a4a194",
    hairStyle: "crop",
    outfit: "vest",
    coat: "#404b54",
    shirt: "#e6e5d8",
    trousers: "#404b54",
    shoes: "#32363a",
    build: 1.09,
    stance: "composed",
    bodyType: "male",
    tie: "#806f88",
    pattern: "pinstripe",
    glasses: true,
    bag: "briefcase",
  },
  {
    id: "office-yeon",
    name: "연화",
    nameEn: "Yeonhwa",
    category: "leadership",
    subtitle: "이사회 의장 · 실버 올림머리와 코트",
    subtitleEn: "Board chair · silver bun and coat",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#c8c3b5",
    hairStyle: "bun",
    outfit: "coat",
    coat: "#9b896b",
    shirt: "#f0e3cc",
    trousers: "#52594f",
    shoes: "#493f32",
    build: 1.18,
    stance: "composed",
    bodyType: "female",
    neckwear: "scarf",
    lower: "skirt",
    skirtLength: "long",
    bag: "briefcase",
  },
  {
    id: "office-dohun",
    name: "도훈",
    nameEn: "Dohun",
    category: "leadership",
    subtitle: "창업자 · 곱슬머리와 실용적인 후드",
    subtitleEn: "Founder · curls and practical hoodie",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#3a3029",
    hairStyle: "curls",
    outfit: "hoodie",
    coat: "#4f655e",
    shirt: "#e9d7b8",
    trousers: "#565552",
    shoes: "#383c37",
    build: 1.1,
    stance: "relaxed",
    bodyType: "male",
    glasses: true,
    bag: "backpack",
    accessory: "notebook",
  },
  {
    id: "office-suhye",
    name: "수혜",
    nameEn: "Suhye",
    category: "leadership",
    subtitle: "영업 총괄 · 포니테일과 선명한 수트",
    subtitleEn: "Sales director · ponytail and statement suit",
    skin: "#795037",
    skinVariant: "black",
    hair: "#282322",
    hairStyle: "pony",
    outfit: "suit",
    coat: "#975e4c",
    shirt: "#f3e6ce",
    trousers: "#975e4c",
    shoes: "#45342b",
    build: 1.02,
    stance: "bright",
    bodyType: "female",
    neckwear: "bow",
    lower: "wide",
    bag: "briefcase",
  },
  {
    id: "office-jaewon",
    name: "재원",
    nameEn: "Jaewon",
    category: "leadership",
    subtitle: "전략 고문 · 은빛 웨이브와 터틀넥",
    subtitleEn: "Strategy adviser · silver waves and turtleneck",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#ada99f",
    hairStyle: "wave",
    outfit: "coat",
    coat: "#4f6369",
    shirt: "#a9b3a2",
    trousers: "#505652",
    shoes: "#393b36",
    build: 1.23,
    stance: "relaxed",
    bodyType: "male",
    neckwear: "turtleneck",
    glasses: true,
    accessory: "notebook",
  },
  {
    id: "office-daeun",
    name: "다은",
    nameEn: "Daeun",
    category: "creative",
    subtitle: "문학 편집자 · 긴 머리와 긴 스커트",
    subtitleEn: "Fiction editor · long hair and long skirt",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#584030",
    hairStyle: "long",
    outfit: "blouse",
    coat: "#bdab88",
    shirt: "#bdab88",
    trousers: "#5f705c",
    shoes: "#574436",
    build: 1.01,
    stance: "relaxed",
    bodyType: "female",
    lower: "skirt",
    skirtLength: "long",
    neckwear: "bow",
    accessory: "notebook",
  },
  {
    id: "office-jiseok",
    name: "지석",
    nameEn: "Jiseok",
    category: "creative",
    subtitle: "번역 편집자 · 곱슬머리와 체크 베스트",
    subtitleEn: "Translation editor · curls and checked vest",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#3b332d",
    hairStyle: "curls",
    outfit: "vest",
    coat: "#a18e71",
    shirt: "#e3d7c0",
    trousers: "#686057",
    shoes: "#473b30",
    build: 1.19,
    stance: "composed",
    bodyType: "male",
    pattern: "check",
    glasses: true,
    bag: "shoulder",
  },
  {
    id: "office-seona",
    name: "선아",
    nameEn: "Seona",
    category: "creative",
    subtitle: "북디자이너 · 땋은 머리와 아틀리에 코트",
    subtitleEn: "Book designer · braids and atelier coat",
    skin: "#795037",
    skinVariant: "black",
    hair: "#352924",
    hairStyle: "braids",
    outfit: "coat",
    coat: "#71867b",
    shirt: "#ddcba9",
    trousers: "#4d525c",
    shoes: "#49403a",
    build: 0.98,
    stance: "bright",
    bodyType: "female",
    lower: "wide",
    neckwear: "turtleneck",
    bag: "shoulder",
  },
  {
    id: "office-haram",
    name: "하람",
    nameEn: "Haram",
    category: "classic",
    subtitle: "해외 판권 담당 · 스카프와 더블 수트",
    subtitleEn: "Foreign rights agent · scarf and double suit",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#573d30",
    hairStyle: "bob",
    outfit: "double-breasted",
    coat: "#746277",
    shirt: "#ebdfc5",
    trousers: "#746277",
    shoes: "#453c45",
    build: 1.05,
    stance: "composed",
    bodyType: "female",
    neckwear: "scarf",
    bag: "briefcase",
    lower: "skirt",
    skirtLength: "knee",
  },
  {
    id: "office-chan",
    name: "찬영",
    nameEn: "Chanyoung",
    category: "casual",
    subtitle: "제작 관리 · 셔츠와 공방 사원증",
    subtitleEn: "Print production · work shirt and ID badge",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#4c4237",
    hairStyle: "crop",
    outfit: "shirt",
    coat: "#b7ac8c",
    shirt: "#b7ac8c",
    trousers: "#647066",
    shoes: "#493d2e",
    build: 1.31,
    stance: "relaxed",
    bodyType: "male",
    accessory: "badge",
    lower: "wide",
    bag: "backpack",
  },
  {
    id: "office-eunsol",
    name: "은솔",
    nameEn: "Eunsol",
    category: "creative",
    subtitle: "교정 교열자 · 올림머리와 니트 카디건",
    subtitleEn: "Copy editor · bun and knitted cardigan",
    skin: "#a37151",
    skinVariant: "brown",
    hair: "#6a5647",
    hairStyle: "bun",
    outfit: "cardigan",
    coat: "#a58c83",
    shirt: "#ede3ce",
    trousers: "#716954",
    shoes: "#514438",
    build: 1.16,
    stance: "composed",
    bodyType: "female",
    pattern: "knit",
    glasses: true,
    lower: "skirt",
    skirtLength: "long",
    accessory: "notebook",
  },
  {
    id: "office-sejin",
    name: "세진",
    nameEn: "Sejin",
    category: "classic",
    subtitle: "협상 전문가 · 가르마와 핀스트라이프",
    subtitleEn: "Negotiator · side part and pinstripes",
    skin: "#795037",
    skinVariant: "black",
    hair: "#383735",
    hairStyle: "part",
    outfit: "double-breasted",
    coat: "#3f545c",
    shirt: "#e6e2d5",
    trousers: "#3f545c",
    shoes: "#33383a",
    build: 1.17,
    stance: "composed",
    bodyType: "male",
    pattern: "pinstripe",
    tie: "#ad8955",
    bag: "briefcase",
  },
  {
    id: "office-hyo",
    name: "효주",
    nameEn: "Hyoju",
    category: "casual",
    subtitle: "서점 영업 · 짧은 단발과 편안한 베스트",
    subtitleEn: "Bookshop sales · short bob and easy vest",
    skin: "#bb8962",
    skinVariant: "bronze",
    hair: "#845e40",
    hairStyle: "bob",
    outfit: "vest",
    coat: "#a6ad8a",
    shirt: "#eddec5",
    trousers: "#7a6c59",
    shoes: "#564734",
    build: 1.09,
    stance: "bright",
    bodyType: "female",
    pattern: "knit",
    lower: "wide",
    bag: "shoulder",
    accessory: "notebook",
  },
  {
    id: "office-yumin",
    name: "유민",
    nameEn: "Yumin",
    category: "classic",
    subtitle: "파트너십 매니저 · 웨이브와 노타이 수트",
    subtitleEn: "Partnership manager · waves and an open-collar suit",
    skin: "#efc3a0",
    skinVariant: "light",
    hair: "#4a3b30",
    hairStyle: "wave",
    outfit: "suit",
    coat: "#8b8e7b",
    shirt: "#f1e4ce",
    trousers: "#8b8e7b",
    shoes: "#5b4637",
    build: 0.97,
    stance: "bright",
    bodyType: "male",
    bag: "briefcase",
    accessory: "badge",
  },
  {
    id: "office-garam",
    name: "가람",
    nameEn: "Garam",
    category: "creative",
    subtitle: "작가 매니저 · 포니테일과 넉넉한 코트",
    subtitleEn: "Author liaison · ponytail and roomy coat",
    skin: "#c7a07a",
    skinVariant: "olive",
    hair: "#382d28",
    hairStyle: "pony",
    outfit: "coat",
    coat: "#b48161",
    shirt: "#e6cfac",
    trousers: "#65686a",
    shoes: "#4a3e35",
    build: 1.24,
    stance: "relaxed",
    bodyType: "female",
    neckwear: "scarf",
    lower: "wide",
    bag: "shoulder",
    glasses: true,
  },
];
